/**
 * Discovery Endpoint for AI Agents
 * Provides machine-readable service catalog optimized for Bazaar and agent discovery
 */

import type { Context } from "hono";
import { PRICING, FREE_TIER } from "../config";
import { getPriceRange } from "../services/pricing";
import type { Env } from "../types";

// Service catalog with rich metadata for AI agent discovery
const SERVICE_CATALOG = {
    name: "WebLens",
    version: "2.0.0",
    tagline: "Give your AI agents web superpowers",
    description: "Premium Web Intelligence API - Give your AI agents web superpowers with x402 micropayments. No API keys, no accounts, just pay per request with USDC on Base.",
    baseUrl: "https://api.weblens.dev",
    protocol: {
        name: "x402",
        version: 2,
        network: "base",
        token: "USDC",
        facilitator: "payai+cdp",
        bazaarListed: false,
    },
    documentation: {
        interactive: "/docs",
        openapi: "/openapi.json",
        llms: "/llms.txt",
        mcp: "/mcp/info",
    },
    whyChooseUs: [
        "Zero friction - No accounts, API keys, or subscriptions",
        "AI-optimized - Structured outputs designed for autonomous agents",
        "Instant settlement - Payments settle in ~1-2 seconds on Base",
        "No fees - x402 protocol has 0 platform fees",
        "Bazaar listed - Discoverable via Coinbase Bazaar",
        "MCP support - Native Model Context Protocol integration",
        "Cache discount - 70% off for cached responses",
        "Free previews - POST /preview returns the price and a real response sample before you pay",
        "ERC-8004 ready - Off-chain registration document, per-call receipts, and hosted feedback documents",
    ],
    capabilities: [
        "web-scraping",
        "javascript-rendering",
        "screenshot-capture",
        "web-search",
        "news-search",
        "image-search",
        "local-business-data",
        "shopping-search",
        "academic-search",
        "keyword-autocomplete",
        "trend-analysis",
        "youtube-transcripts",
        "grounded-answers",
        "deep-research",
        "cited-research",
        "bulk-page-contents",
        "site-mapping",
        "sitemap-discovery",
        "web-crawling",
        "data-extraction",
        "ai-powered-analysis",
        "pdf-extraction",
        "url-monitoring",
        "persistent-memory",
        "batch-operations",
        "url-comparison",
        "autonomous-context-verification",
        "truth-oracle",
        "web-intelligence",
        "cryptographic-proofs",
        "reputation-aware",
        "free-previews",
        "endpoint-previews",
        "erc-8004",
        "agent-reputation",
        "call-receipts",
    ],
    useCases: [
        "AI agent web browsing and research",
        "Multi-step cited research with source attribution",
        "Automated fact-checking and verification",
        "Content aggregation and monitoring",
        "Whole-site crawling and knowledge base ingestion",
        "Competitive intelligence gathering",
        "Lead generation and data mining",
        "Visual testing and archiving",
        "Document processing and extraction",
        "Multi-source comparison analysis",
        "Persistent agent memory across sessions",
        "Evaluating an endpoint's price and response shape before paying",
        "Citable payment receipts and ERC-8004 feedback for agent reputation",
    ],
    services: [
        {
            endpoint: "/fetch/basic",
            method: "POST",
            name: "Fetch Webpage (Basic)",
            description: "Fast webpage to markdown conversion without JavaScript rendering",
            price: PRICING.fetch.basic,
            tags: ["web-scraping", "markdown", "fast", "static-content"],
            latency: "1-3 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/fetch/pro",
            method: "POST",
            name: "Fetch Webpage (Pro)",
            description: "Full JavaScript rendering with headless Chromium for SPAs and dynamic content",
            price: PRICING.fetch.pro,
            tags: ["web-scraping", "javascript", "spa", "dynamic-content"],
            latency: "3-8 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/fetch/resilient",
            method: "POST",
            name: "Resilient Fetch (Agent Prime)",
            description: "Multi-tier fetch with automatic fallback: native scraper, then headless Chromium for JS-rendered or bot-walled pages.",
            price: PRICING.fetch.resilient,
            tags: ["web-scraping", "resilient", "fallback", "premium"],
            latency: "2-10 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/screenshot",
            method: "POST",
            name: "Screenshot Capture",
            description: "High-quality PNG screenshots with custom viewports and element targeting",
            price: PRICING.screenshot,
            tags: ["screenshot", "visual", "image", "archiving"],
            latency: "2-5 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/search",
            method: "POST",
            name: "Web Search",
            description: `Real-time web search with ranked results via SerpAPI. Set includeContent to also fetch the top result pages as markdown (+${PRICING.contents.perUrl}/result).`,
            price: PRICING.search,
            tags: ["search", "google", "real-time", "information-retrieval"],
            latency: "1-2 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/news",
            method: "POST",
            name: "News Search",
            description: "Real-time news search via Google News. Returns ranked articles with source, date, and thumbnail.",
            price: PRICING.searchVerticals.news,
            tags: ["search", "news", "news-search", "real-time"],
            latency: "1-2 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/images",
            method: "POST",
            name: "Image Search",
            description: "Google Images search. Returns direct image URLs with dimensions, thumbnails, and source pages.",
            price: PRICING.searchVerticals.images,
            tags: ["search", "images", "image-search", "visual"],
            latency: "1-2 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/places",
            method: "POST",
            name: "Places Search",
            description: "Local business search via Google Local. Returns names, addresses, ratings, reviews, phone numbers, websites, and coordinates.",
            price: PRICING.searchVerticals.places,
            tags: ["search", "places", "local-business-data", "maps"],
            latency: "1-3 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/shopping",
            method: "POST",
            name: "Shopping Search",
            description: "Google Shopping product search. Returns products with prices, sellers, ratings, and links.",
            price: PRICING.searchVerticals.shopping,
            tags: ["search", "shopping", "products", "e-commerce"],
            latency: "1-2 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/scholar",
            method: "POST",
            name: "Scholar Search",
            description: "Google Scholar academic search. Returns papers with snippets, publication info, and citation counts.",
            price: PRICING.searchVerticals.scholar,
            tags: ["search", "scholar", "academic", "research-papers"],
            latency: "1-2 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/autocomplete",
            method: "POST",
            name: "Autocomplete",
            description: "Google Autocomplete suggestions for a partial query. Useful for keyword research and intent discovery.",
            price: PRICING.searchVerticals.autocomplete,
            tags: ["search", "autocomplete", "keywords", "seo"],
            latency: "<1 second",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/search/trends",
            method: "POST",
            name: "Trends",
            description: "Google Trends interest-over-time for a query. Returns a timeline of relative search interest.",
            price: PRICING.searchVerticals.trends,
            tags: ["search", "trends", "trend-analysis", "time-series"],
            latency: "1-3 seconds",
            rateLimit: "100/minute",
        },
        {
            endpoint: "/social/youtube/transcript",
            method: "POST",
            name: "YouTube Transcript",
            description: "Full transcript of any YouTube video with timestamps. Accepts a video ID or any YouTube URL (watch, shorts, youtu.be).",
            price: PRICING.youtubeTranscript,
            tags: ["social", "youtube", "youtube-transcripts", "video"],
            latency: "1-3 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/contents",
            method: "POST",
            name: "Bulk Page Contents",
            description: `Cheap bulk page text: fetch ${PRICING.contents.minUrls}-${PRICING.contents.maxUrls} URLs and get clean markdown, truncated to a per-page cap.`,
            price: `${PRICING.contents.perUrl}/URL`,
            tags: ["web-scraping", "bulk", "markdown", "contents"],
            latency: "2-10 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/answer",
            method: "POST",
            name: "Grounded Answer",
            description: "Grounded answer with inline [n] citations: searches the web, fetches sources, and answers strictly from them.",
            price: PRICING.answer,
            tags: ["research", "answer", "grounded-answers", "citations", "ai-powered"],
            latency: "5-20 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/extract",
            method: "POST",
            name: "Structured Data Extraction",
            description: "Extract data using JSON schema with AI-powered understanding",
            price: PRICING.extract,
            tags: ["extraction", "structured-data", "json-schema", "ai-powered"],
            latency: "3-6 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/extract/smart",
            method: "POST",
            name: "Smart Extraction",
            description: "Natural language data extraction - just describe what you want",
            price: PRICING.smartExtract,
            tags: ["extraction", "natural-language", "ai-powered", "flexible"],
            latency: "4-8 seconds",
            rateLimit: "30/minute",
        },
        {
            endpoint: "/research",
            method: "POST",
            name: "AI Research Assistant",
            description: "One-stop research: search + fetch + AI summary with key findings",
            price: PRICING.research,
            tags: ["research", "ai-summary", "analysis", "comprehensive"],
            latency: "10-30 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/research/deep",
            method: "POST",
            name: "Deep Research (Cited)",
            description: `Multi-step cited research in one synchronous call — no async job or polling. Plans sub-questions, searches each, fetches and dedupes sources, then synthesizes an answer with inline [n] citations, key findings, and gaps. ${PRICING.deepResearch.standard} standard (3 sub-questions, 8 sources) / ${PRICING.deepResearch.deep} deep (5 sub-questions, 12 sources). Long-running: use a generous client timeout.`,
            price: `${PRICING.deepResearch.standard}-${PRICING.deepResearch.deep}`,
            tags: ["research", "deep-research", "cited-research", "citations", "ai-powered"],
            latency: "30-60 seconds",
            rateLimit: "10/minute",
        },
        {
            endpoint: "/batch/fetch",
            method: "POST",
            name: "Batch Fetch",
            description: "Fetch 2-20 URLs in parallel for efficient bulk operations",
            price: `${PRICING.batchFetch.perUrl}/URL`,
            tags: ["batch", "parallel", "bulk", "efficient"],
            latency: "5-15 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/map",
            method: "POST",
            name: "Site Map",
            description: "Discover a site's URLs without fetching page content: robots.txt sitemap directives, sitemap.xml and nested sitemap indexes, falling back to homepage link extraction.",
            price: PRICING.map,
            tags: ["site-mapping", "sitemap-discovery", "urls", "crawling"],
            latency: "1-5 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/crawl",
            method: "POST",
            name: "Site Crawl",
            description: `Bounded same-host BFS crawl returning clean markdown for every page in one synchronous call — no async job or polling. robots.txt honoured by default. Billed on the requested page budget (${PRICING.crawl.minPages}-${PRICING.crawl.maxPages}), not pages returned.`,
            price: `${PRICING.crawl.perPage}/page`,
            tags: ["web-crawling", "site-mapping", "markdown", "bulk"],
            latency: "5-30 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/pdf",
            method: "POST",
            name: "PDF Extraction",
            description: "Extract text and metadata from PDF documents",
            price: PRICING.pdf,
            tags: ["pdf", "document", "text-extraction", "metadata"],
            latency: "2-10 seconds",
            rateLimit: "30/minute",
        },
        {
            endpoint: "/compare",
            method: "POST",
            name: "URL Comparison",
            description: "AI-powered comparison of 2-3 webpages with similarity analysis",
            price: PRICING.compare,
            tags: ["comparison", "analysis", "ai-powered", "diff"],
            latency: "10-20 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/monitor/create",
            method: "POST",
            name: "URL Monitor",
            description: "Create change detection monitors with webhook notifications",
            price: PRICING.monitor.setup,
            tags: ["monitoring", "change-detection", "webhook", "alerts"],
            latency: "1-2 seconds",
            rateLimit: "50/minute",
        },
        {
            endpoint: "/memory/set",
            method: "POST",
            name: "Memory Storage",
            description: "Persistent key-value storage for AI agent context",
            price: PRICING.memory.write,
            tags: ["memory", "storage", "persistence", "agent-context"],
            latency: "<1 second",
            rateLimit: "100/minute",
        },
        // Intelligence Endpoints (Knowledge Arbitrageur)
        {
            endpoint: "/intel/company",
            method: "POST",
            name: "Company Intelligence",
            description: "Comprehensive company deep dive: tech stack, funding, team size, competitors, news. Chains search + batch fetch + AI extraction.",
            price: PRICING.intel.company,
            tags: ["intelligence", "company-research", "ai-powered", "premium"],
            latency: "10-30 seconds",
            rateLimit: "20/minute",
        },
        {
            endpoint: "/intel/market",
            method: "POST",
            name: "Market Research Report",
            description: "AI-powered market research: executive summary, key findings, trends, key players, data points, and recommended actions.",
            price: PRICING.intel.market,
            tags: ["intelligence", "market-research", "ai-powered", "premium"],
            latency: "15-45 seconds",
            rateLimit: "10/minute",
        },
        {
            endpoint: "/intel/competitive",
            method: "POST",
            name: "Competitive Analysis",
            description: "Full competitive analysis: feature matrix, pricing comparison, SWOT analysis, positioning summary.",
            price: PRICING.intel.competitive,
            tags: ["intelligence", "competitive-analysis", "ai-powered", "premium"],
            latency: "15-45 seconds",
            rateLimit: "10/minute",
        },
        {
            endpoint: "/intel/site-audit",
            method: "POST",
            name: "Site Audit",
            description: "Comprehensive SEO, performance, and security audit with actionable recommendations and scoring.",
            price: PRICING.intel.siteAudit,
            tags: ["intelligence", "seo", "audit", "ai-powered", "premium"],
            latency: "5-15 seconds",
            rateLimit: "30/minute",
        },
    ],
    pricing: {
        currency: "USDC",
        network: "base",
        cacheDiscount: "70% off for cached responses",
        noFees: "x402 protocol has 0 fees",
        instantSettlement: "~1-2 seconds on Base",
        priceRange: getPriceRange(),
    },
    integration: {
        mcp: {
            remote: "https://api.weblens.dev/mcp",
            local: "npx -y @weblens/mcp",
            description: "Model Context Protocol for AI agents (Claude, Kiro, etc.)",
        },
        http: {
            baseUrl: "https://api.weblens.dev",
            auth: "x402 v2 payment via Payment-Signature header",
        },
        paymentMethods: [
            {
                name: "x402 (USDC on Base)",
                path: "POST <any paid endpoint>",
                description: "Pay per request with on-chain USDC. No account needed.",
            },
            {
                name: "Credit account (prepaid USDC)",
                path: "POST /credits/buy",
                description: "Deposit USDC once, sign subsequent requests with X-CREDIT-WALLET. 20–40% bonus at $10/$50/$100.",
            },
            {
                name: "Credit account (prepaid via card)",
                path: "POST /credits/deposit/fiat",
                description: "Zero-crypto onboarding. Pay with card via Stripe Checkout; credits land on the wallet address you supply. Minimum $2.",
            },
        ],
    },
    agentQuickStart: {
        step0: "Try it instantly! GET /r/https://example.com — zero friction, no wallet, no POST body needed",
        step1: "Call any paid endpoint (e.g., POST /fetch/basic with {url: 'https://example.com'})",
        step2: "Receive 402 Payment Required — read the PAYMENT-REQUIRED response header (base64-encoded JSON) for amount, asset, payTo, accepts",
        step3: "Sign USDC payment using your wallet (Base network)",
        step4: "Retry with the Payment-Signature header containing the signed payload",
        step5: "Receive data; settlement receipt is in the PAYMENT-RESPONSE response header",
    },
    freeTier: {
        description: "Try WebLens free — no wallet or payment needed",
        endpoints: [
            {
                endpoint: "/r/{url}",
                method: "GET",
                name: "Reader Mode",
                description: "Zero-friction: just GET /r/ + any URL → markdown. No auth, no POST body.",
                price: "FREE",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "reader", "zero-friction", "viral"],
            },
            {
                endpoint: "/s/{query}",
                method: "GET",
                name: "Search Reader",
                description: "Zero-friction: just GET /s/ + query → search results. No auth, no POST body.",
                price: "FREE",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "search", "zero-friction", "viral"],
            },
            {
                endpoint: "/free/fetch",
                method: "POST",
                name: "Free Fetch",
                description: "Fetch any webpage (content truncated to 2000 chars)",
                price: "FREE",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "web-scraping", "trial"],
            },
            {
                endpoint: "/free/search",
                method: "POST",
                name: "Free Search",
                description: `Web search (max ${FREE_TIER.searchMaxResults} results)`,
                price: "FREE",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "search", "trial"],
            },
            {
                endpoint: "/preview",
                method: "POST",
                name: "Endpoint Preview",
                description: "See a paid endpoint's live price and a real sample of its response shape before paying. Body: {endpoint, url?}. Endpoints with no paid upstream (/fetch/basic, /contents, /map) also run a real truncated LIVE preview when you pass a url; SerpAPI- and Anthropic-backed endpoints return the recorded sample instead, because free live runs there would burn upstream credits. 404 for an endpoint that is not sold.",
                price: "free",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "free-previews", "endpoint-previews", "evaluation", "pricing"],
            },
            {
                endpoint: "/.well-known/agent-registration.json",
                method: "GET",
                name: "ERC-8004 Registration Document",
                description: "The ERC-8004 registration document (registration-v1): name, description, image, services, x402Support, payment, and feedback endpoints. Off-chain only — WebLens is not registered on-chain, holds no agent id, and writes nothing to any registry, so registrations is empty and supportedTrust is [\"feedback\"].",
                price: "free",
                rateLimit: "none",
                tags: ["free", "erc-8004", "agent-reputation", "identity", "discovery"],
            },
            {
                endpoint: "/receipts/{requestId}",
                method: "GET",
                name: "Call Receipt",
                description: "Receipt for a paid call: endpoint, status, outcome, price, payment method, network, payTo. Paid responses carry X-Receipt-Id and X-Receipt-Url headers; receipts are kept 30 days. The mac field, when present, is a symmetric HMAC tag verifiable only by the key holder — not a third-party-verifiable signature.",
                price: "free",
                rateLimit: "none",
                tags: ["free", "erc-8004", "call-receipts", "payment-evidence"],
            },
            {
                endpoint: "/feedback",
                method: "POST",
                name: "Host ERC-8004 Feedback",
                description: "Host a buyer-authored ERC-8004 feedback document and get back the (feedbackURI, feedbackHash) pair giveFeedback() expects. Required fields: agentRegistry, agentId, clientAddress, createdAt, value, valueDecimals. Stored verbatim — WebLens neither authors nor alters it and never calls the registry.",
                price: "free",
                rateLimit: `${FREE_TIER.maxRequestsPerHour}/hour`,
                tags: ["free", "erc-8004", "agent-reputation", "feedback"],
            },
            {
                endpoint: "/feedback/{id}",
                method: "GET",
                name: "Get Hosted Feedback",
                description: "Serves a hosted feedback document byte-for-byte, so its keccak-256 hash matches the feedbackHash returned when it was stored. This URL is the feedbackURI.",
                price: "free",
                rateLimit: "none",
                tags: ["free", "erc-8004", "agent-reputation", "feedback"],
            },
        ],
        limits: {
            requestsPerHour: FREE_TIER.maxRequestsPerHour,
            fetchContentLength: FREE_TIER.fetchMaxContentLength,
            searchMaxResults: FREE_TIER.searchMaxResults,
        },
        upgrade: "Use paid endpoints for full content, unlimited access, and premium features",
    },
};

/**
 * Discovery endpoint handler - returns full service catalog
 */
export function discoveryHandler(c: Context<{ Bindings: Env }>) {
    const baseUrl = new URL(c.req.url).origin;

    // Only advertise the fiat onramp when Stripe is actually configured —
    // otherwise /discovery promises a payment method that `/credits/deposit/fiat`
    // would answer with 503.
    const fiatEnabled = Boolean(c.env.STRIPE_SECRET_KEY);
    const paymentMethods = SERVICE_CATALOG.integration.paymentMethods.filter(
        (m) => fiatEnabled || !m.path.includes("/credits/deposit/fiat")
    );

    return c.json({
        ...SERVICE_CATALOG,
        baseUrl,
        documentation: {
            ...SERVICE_CATALOG.documentation,
            interactive: `${baseUrl}/docs`,
            openapi: `${baseUrl}/openapi.json`,
            llms: `${baseUrl}/llms.txt`,
            mcp: `${baseUrl}/mcp/info`,
        },
        integration: {
            ...SERVICE_CATALOG.integration,
            paymentMethods,
        },
        _links: {
            self: `${baseUrl}/discovery`,
            docs: `${baseUrl}/docs`,
            openapi: `${baseUrl}/openapi.json`,
            health: `${baseUrl}/health`,
            mcp: `${baseUrl}/mcp`,
        },
    });
}

/**
 * Well-known x402 discovery endpoint (/.well-known/x402)
 * Standard location for x402 service discovery
 */
export function wellKnownX402Handler(c: Context<{ Bindings: Env }>) {
    const baseUrl = new URL(c.req.url).origin;

    return c.json({
        x402Version: 2,
        name: "WebLens",
        tagline: "Give your AI agents web superpowers with verified data",
        description: "Premium Web Intelligence API with x402 micropayments. Features Autonomous Context Verification (ACV), Dynamic Pricing, and Truth-as-a-Service for AI agents.",
        baseUrl,
        facilitator: "payai+cdp",
        network: "base",
        token: "USDC",
        bazaarListed: false,
        keywords: [
            "web-scraping", "ai-agent", "x402", "micropayments", "truth-oracle",
            "context-verification", "web-intelligence", "data-extraction",
            "headless-browser", "research-assistant", "news-search",
            "local-business-data", "youtube-transcripts", "grounded-answers",
            "deep-research", "cited-research",
            "site-mapping", "sitemap-discovery", "web-crawling",
            "free-previews", "erc-8004", "agent-reputation", "call-receipts"
        ],
        capabilities: SERVICE_CATALOG.capabilities,
        endpoints: SERVICE_CATALOG.services.map(s => ({
            path: s.endpoint,
            method: s.method,
            name: s.name,
            description: s.description,
            price: s.price,
            tags: s.tags,
            latency: s.latency,
        })),
        pricing: {
            currency: "USDC",
            range: getPriceRange(),
            cacheDiscount: "70%",
        },
        documentation: `${baseUrl}/docs`,
        openapi: `${baseUrl}/openapi.json`,
        llms: `${baseUrl}/llms.txt`,
        mcp: `${baseUrl}/mcp`,
        discovery: `${baseUrl}/discovery`,
        freeTier: {
            description: "Try WebLens free — no wallet needed",
            reader: `${baseUrl}/r/https://example.com`,
            searchReader: `${baseUrl}/s/cloudflare+workers`,
            fetch: `${baseUrl}/free/fetch`,
            search: `${baseUrl}/free/search`,
            preview: `${baseUrl}/preview`,
            rateLimit: `${FREE_TIER.maxRequestsPerHour} requests/hour`,
        },
        erc8004: {
            description: "Off-chain ERC-8004 surfaces only. WebLens is not registered on-chain, holds no agent id, and writes nothing to any registry.",
            registration: `${baseUrl}/.well-known/agent-registration.json`,
            receipt: `${baseUrl}/receipts/{requestId}`,
            submitFeedback: `${baseUrl}/feedback`,
            feedbackDocument: `${baseUrl}/feedback/{id}`,
            hashAlgorithm: "keccak256",
            supportedTrust: ["feedback"],
        },
    });
}
